# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - bonhomme.vincent@gmail.com
    on_success: change
    on_failure: change

#before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true

