# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#   - Rscript -e 'pkgdown::build_site()'

language: r
cache: packages

r:
  - release

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - bonhomme.vincent@gmail.com
    on_success: change
    on_failure: change


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

