---
title: "Momocs to MomX"
author: "Vincent Bonhomme"
format: html
---

# Preamble

I started writing Momocs in early 2011 while doing my first postdoc at the French Institute of Pondicherry, India, based on Julien Claude's book Morphometrics with R and using some developments by Sandrine Picq. I was hired by Cédric Gaucherel who was a colleague, a companion, and remains a friend to this day. 

By then, I actually knew very little about morphometrics, this was pretty much my first package, I had no developing experience, we were in a pre-tidyverse era, and R overall was far from what it became. But I was really motivated to do some shape analysis myself after 3 years of PhD on Nepenthes with such tempting curves that I could only dream of at the time. 

From Julien's book to a unified package there was some thinking which, of course, proved approximate when looking backwards. From the companion paper published in JSS, cited ~800 times, you can see that my plan was to cover all morphometrics. Once published, I quickly realized that I had to think more about the latent grammar in morphometrics, how landmarks, curves, outlines, and measurements relate to shape quantification and, on the coding side, how to implement this. Hence the early erratic path from S4 to S3 of Momocs.

Around that time, I started doing some consulting and training in R, which allowed me to realize how much of a beginneR I actually was! On the research side, I was hosted at the late CBAE in Montpellier, now part of ISEM, around (and often surrounded by) Jean-Fréderic Terral, Laurent Bouby, Allowen Evin, Sarah Ivorra, Clémence Pagnoux, and Muriel Gros-Balthazard among others. I started the real stuff there, with complex datasets, mostly working on grapevine pips. I then realized that R was quite poor at handling datasets, that Momocs was totally broken in that respect. Then the first bricks of the tidyverse made us all rich.

A couple of years later, after the first studies and quite early adoption of Momocs, notably by archaeobotanists (ourselves aside), I started a new post-doc in Sheffield, UK with a wonderful team around Glynis Jones. There, and then back at ISEM for two other postdocs, I mostly worked on statistical approaches and navigated through the jungle of special cases. 

I was dreaming by then that everything morphometrics was a gentle tibble, that ggplot2 could handle morphospace drawing in the background, and that packages could take 20 seconds to R CMD CHECK. I also became a father for the first time and let Momocs become a chubby baby with 20k lines of code, a palimpsest of my journey through coding, life, humour, and morphometrics (possibly not in that order).

The COVID era pushed me to rebuild everything from scratch and the first MomX attempt dates back to early 2020. Since then I've been very busy fathering, doing consultancy, rebuilding houses, launching another business of dry-separating toilets—in brief, caught by _le tourbillon de la vie_. I needed time to think and rewrite all of this and make MomX come true. But time is money.

I finally found a way to fund myself and here we are. In the meantime, the tidyverse and tidymodels became really mature; so did I. And AI became quite good at scraping code, suggesting workarounds, and doing the tedious parts of packaging faster and better. Quite a funny coincidence that two Claude became such an inspiration and companion through Momocs and MomX history.

# MomX rationale and design principles

 * The world, and at least myself, needs complete and user-friendly ecosystem for morphometrics
 * Compartiment key processes into well-defined, interoperable packages that go together well.
 * Each package should solve a single task, and do it well.
 * Each package should be easy to understand, improve, debug, update.

MomX embraces and owns much to the tidy manifesto. MomX kind of theorise the programming side of morphometrics, or at least itself (yes, infinite loop). Tibbles are the answer.
 * Make full use of the tidyverse, so that implementation is really lighter now

# Momocs to Momocs2

## coo/get/measure

| Function | Input | Output (tibble) | Output (matrix/list) | Purpose |
|----------|-------|-----------------|---------------------|---------|
| `coo_*` | coo | tibble (coo replaced) | matrix/list | Transform shape |
| `get_*` | coo | list/vector (extracted) | various | Extract for processing |
| `measure_*` | coo | tibble (column added) | scalar(s) | Add measurement column |

## full list of function changes

All functions :

Core trasnformations ----
coo_center / coo_centre -> coo_centre remove
coo_trans -> coo_translate
coo_rotate / coo_rotatecenter -> same / coo_rotate_around
coo_scale / coo_scalex / coo_scaley -> coo_scale. rm scalex and scaley
coo_flipx / coo_flipy ->  coo_flip_x/yaxis use axes
NEW: coo_flip_x/y allows any x/y intercept (centroid by default).
coo_shearx / coo_sheary -> coo_shear_x/y
coo_untiltx -> ?

Alignement ----
coo_align -> now use centroid as center.
NEW: coo_align_minor uses 2nd svd axes (~2nd PC)
coo_aligncalliper TODO
coo_alignminradius TODO
coo_alignxax TODO
coo_baseline / coo_bookstein : same name, beter implementation
coo_slide -> same behaviour and now guarantee to handle funny values
coo_slidedirection -> coo_slide_direction
NEW: coo_slide_closest -> can slide to closest of an arbitrary point
coo_slidegap -> same

Sampling & smoothing -----
coo_sample  -> same name but now uses a real approximation along arc length / curvilinear abscissa. Using aprox also allows interpolate.
coo_sample_prop -> same
coo_samplerr > TODO
coo_interpolate -> now included in coo_sample
coo_smooth -> same but better implemented
coo_smoothcurve -> coo_smooth_fixed


Point manipulation: -----
coo_slice -> coo_open # TODO group with coo_open_up, etc.
coo_trim -> coo_head
coo_trimbottom -> coo_tail
coo_trimtop -> coo_head
coo_extract -> same
coo_rev
coo_jitter
coo_close
coo_unclose
coo_force2close

# RETURN SCALARS
Area & perimeter:
measure_area          # coo_area
measure_perim         # coo_perim
measure_perimcum      # was coo_perimcum (cumulative - vector), now splitted in get_perim_cum
measure_perimpts      # coo_perimpts (per point - vector)

Size & dimensions:
measure_centsize      # coo_centsize
measure_length        # coo_length
measure_width         # coo_width
measure_lw            # coo_lw (length/width ratio)
measure_calliper      # coo_calliper

Shape descriptors:
measure_circularity           # coo_circularity
measure_circularityharalick   # coo_circularityharalick
measure_circularitynorm       # coo_circularitynorm
measure_convexity             # coo_convexity
measure_solidity              # coo_solidity
measure_eccentricityboundingbox  # coo_eccentricityboundingbox
measure_eccentricityeigen     # coo_eccentricityeigen
measure_elongation            # coo_elongation
measure_rectangularity        # coo_rectangularity
measure_rectilinearity        # coo_rectilinearity

Distance and angles:
measure_centdist         # coo_centdist (vector)
measure_dxy              # coo_dxy (vector)
measure_diffrange        # coo_diffrange
measure_angle_edges      # coo_angle_edges (vector)
measure_angle_tangent    # coo_angle_tangent (vector)
measure_tangle           # coo_tangle (vector)

Ranges and positions:
measure_range            # coo_range (2 values)
measure_centpos          # coo_centpos
measure_nb               # coo_nb (number of points)

Truss and scalars
measure_truss            # coo_truss
measure_scalars          # coo_scalars

Plotting functions
coo_plot -> pile
coo_draw -> draw_*
coo_draw_rads -> removed
coo_arrows -> TODO ? viz ?
coo_lolli -> viz
coo_oscillo -> viz
coo_ruban -> viz
coo_tac -> get ? # TODO
coo_listpanel -> mosaic

stack -> pile (to avoid conflct with existing stack)
panel -> mosaic

MISC (selon Claude)

coo_boundingbox       # bbox corners coordinates? -> get bounding box ?
coo_chull             # convex hull coordinates # TODO
coo_chull_onion       # -> get_chull # TODO
coo_ldk               # removed. See Momacs.
coo_range_enlarge     # removed

coo_check             # validation# TODO
coo_is_closed         # logical check # TODO but not a coo
coo_template          # same name # TODO (and add to mosaic !!!)
coo_template_relatively  # TODO

coo_up / coo_down / coo_left / coo_right  # TODO
coo_likely_clockwise / coo_likely_anticlockwise  # logical check

coo_intersect_angle
coo_intersect_direction
coo_intersect_segment



# Momacs

# The coming teenage of MomX


