usethis::use_gpl3_license()
usethis::use_readme_rmd()
usethis::use_code_of_conduct(contact = "bonhomme.vincent@gmail.com")
usethis::use_news_md()
usethis::use_cran_badge()
usethis::use_lifecycle_badge("experimental")
usethis::use_package("dplyr", "Suggests")

usethis::use_git()
usethis::use_github("MomX")

usethis::use_pkgdown_github_pages()
# usethis::use_github_action("check-standard")
# usethis::use_github_action("test-coverage")
# usethis::use_github_action("pkgdown")
